# fly.toml app configuration file generated for savage-influxdb on 2026-05-21T20:55:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'savage-influxdb'
primary_region = 'sjc'

[build]
  image = 'influxdb:2.7'

[env]
  DOCKER_INFLUXDB_INIT_BUCKET = 'timeseries'
  DOCKER_INFLUXDB_INIT_MODE = 'setup'
  DOCKER_INFLUXDB_INIT_ORG = 'savage'

[[mounts]]
  source = 'influx_data'
  destination = '/var/lib/influxdb2'
  initial_size = '10gb'

[http_service]
  internal_port = 8086
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
